export const INIT_MAP = 'INIT_MAP';
export const MAPVIEW_LOAD_ERROR = 'MAPVIEW_LOAD_ERROR';
export const TOGGLE_VISIBLE_LAYER = 'TOGGLE_VISIBLE_LAYER';
export const LAYER_INFO_RECEIVED = 'LAYER_INFO_RECEIVED';
export const FETCHING_LAYER_INFO = 'FETCHING_LAYER_INFO';
